FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY . /app

RUN npm ci --legacy-peer-deps
RUN npm run build

FROM node:22-bookworm-slim

WORKDIR /app
COPY --from=build /app /app

EXPOSE 3000
ENV PORT=3000

CMD ["npm", "run", "start"]
