export const newsCategories = {
  all: 'すべて',
  crisis: '災害',
  virus: '感染症',
  accident: '事故',
  incident: '事件',
  children: '児童虐待',
  drug: '薬物乱用',
  nikkei: '経済',
  politics: '政治',
  sports: 'スポーツ',
  poverty: '貧困',
  poverty_child: '貧困（子ども）',
  poverty_disparity: '貧困（経済格差）',
  poverty_food: '貧困（食）',
  poverty_non_regular: '貧困（非正規雇用）',
  poverty_one_parent: '貧困（片親）',
};
