export const newsCategories = {
  all: 'すべて',
  crisis: '災害',
  virus: '感染症',
  accident: '事故',
  incident: '事件',
  child_abuse: '児童虐待',
  drug_abuse: '薬物乱用',
  nikkei: '経済',
  politics: '政治',
  sports: 'スポーツ',
  refugee: '難民',
  poverty: '貧困',
  poverty_child: '貧困（子ども）',
  poverty_disparity: '貧困（格差）',
  poverty_food: '貧困（食）',
  poverty_non_regular: '貧困（非正規雇用）',
  poverty_one_parent: '貧困（ひとり親）',
  poverty_senior: '貧困（高齢者）',
  poverty_tech_intern: '貧困（技能実習生）',
  poverty_woman: '貧困（女性）',
};
