on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

name: daily jobs
jobs:
  daily-jobs:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.CLOUDFLARE_D1_DATABASE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    strategy:
      matrix:
        job-name:
          - river
          - dispatch
          - massmedia
          - hatebu
    steps:
      - uses: actions/checkout@master
      - name: Extract node version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm run job:${{ matrix['job-name'] }}
